In [1]:
import pandas as pd

# Load the ORIGINAL dataset
df = pd.read_csv("../data/raw/fraud_oracle.csv")

# Make a copy for cleaning
df_clean = df.copy()

print("Original shape:", df.shape)
print("Cleaning copy shape:", df_clean.shape)

Original shape: (15420, 33)
Cleaning copy shape: (15420, 33)

In [2]:
df_clean = df_clean.drop_duplicates()

In [3]:
df.isnull().sum()

Month                   0
WeekOfMonth             0
DayOfWeek               0
Make                    0
AccidentArea            0
DayOfWeekClaimed        0
MonthClaimed            0
WeekOfMonthClaimed      0
Sex                     0
MaritalStatus           0
Age                     0
Fault                   0
PolicyType              0
VehicleCategory         0
VehiclePrice            0
FraudFound_P            0
PolicyNumber            0
RepNumber               0
Deductible              0
DriverRating            0
Days_Policy_Accident    0
Days_Policy_Claim       0
PastNumberOfClaims      0
AgeOfVehicle            0
AgeOfPolicyHolder       0
PoliceReportFiled       0
WitnessPresent          0
AgentType               0
NumberOfSuppliments     0
AddressChange_Claim     0
NumberOfCars            0
Year                    0
BasePolicy              0
dtype: int64

In [6]:
df.dtypes

Month                     str
WeekOfMonth             int64
DayOfWeek                 str
Make                      str
AccidentArea              str
DayOfWeekClaimed          str
MonthClaimed              str
WeekOfMonthClaimed      int64
Sex                       str
MaritalStatus             str
Age                     int64
Fault                     str
PolicyType                str
VehicleCategory           str
VehiclePrice              str
FraudFound_P            int64
PolicyNumber            int64
RepNumber               int64
Deductible              int64
DriverRating            int64
Days_Policy_Accident      str
Days_Policy_Claim         str
PastNumberOfClaims        str
AgeOfVehicle              str
AgeOfPolicyHolder         str
PoliceReportFiled         str
WitnessPresent            str
AgentType                 str
NumberOfSuppliments       str
AddressChange_Claim       str
NumberOfCars              str
Year                    int64
BasePolicy                str
dtype: object

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df_clean = df.copy()

In [9]:
df_clean

,Month,WeekOfMonth,DayOfWeek,Make,AccidentArea,DayOfWeekClaimed,MonthClaimed,WeekOfMonthClaimed,Sex,MaritalStatus,...,AgeOfVehicle,AgeOfPolicyHolder,PoliceReportFiled,WitnessPresent,AgentType,NumberOfSuppliments,AddressChange_Claim,NumberOfCars,Year,BasePolicy
0,Dec,5,Wednesday,Honda,Urban,Tuesday,Jan,1,Female,Single,...,3 years,26 to 30,No,No,External,none,1 year,3 to 4,1994,Liability
1,Jan,3,Wednesday,Honda,Urban,Monday,Jan,4,Male,Single,...,6 years,31 to 35,Yes,No,External,none,no change,1 vehicle,1994,Collision
2,Oct,5,Friday,Honda,Urban,Thursday,Nov,2,Male,Married,...,7 years,41 to 50,No,No,External,none,no change,1 vehicle,1994,Collision
3,Jun,2,Saturday,Toyota,Rural,Friday,Jul,1,Male,Married,...,more than 7,51 to 65,Yes,No,External,more than 5,no change,1 vehicle,1994,Liability
4,Jan,5,Monday,Honda,Urban,Tuesday,Feb,2,Female,Single,...,5 years,31 to 35,No,No,External,none,no change,1 vehicle,1994,Collision
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15415,Nov,4,Friday,Toyota,Urban,Tuesday,Nov,5,Male,Married,...,6 years,31 to 35,No,No,External,none,no change,1 vehicle,1996,Collision
15416,Nov,5,Thursday,Pontiac,Urban,Friday,Dec,1,Male,Married,...,6 years,31 to 35,No,No,External,more than 5,no change,3 to 4,1996,Liability
15417,Nov,5,Thursday,Toyota,Rural,Friday,Dec,1,Male,Single,...,5 years,26 to 30,No,No,External,1 to 2,no change,1 vehicle,1996,Collision
15418,Dec,1,Monday,Toyota,Urban,Thursday,Dec,2,Female,Married,...,2 years,31 to 35,No,No,External,more than 5,no change,1 vehicle,1996,All Perils
15419,Dec,2,Wednesday,Toyota,Urban,Thursday,Dec,3,Male,Single,...,5 years,26 to 30,No,No,External,1 to 2,no change,1 vehicle,1996,Collision

In [10]:
# Check for duplicate rows
duplicate_count = df_clean.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

In [11]:
# Check missing values
missing_count = df_clean.isnull().sum()

print(missing_count[missing_count > 0])

Series([], dtype: int64)

In [12]:


# Check common text representations of missing data

for col in df_clean.select_dtypes(include="object").columns:
    values = df_clean[col].astype(str).str.strip().str.lower()

    count = values.isin([
        "unknown",
        "n/a",
        "na",
        "none",
        "?",
        "missing",
        ""
    ]).sum()

    if count > 0:
        print(f"{col}: {count}")

Days_Policy_Accident: 55
Days_Policy_Claim: 1
PastNumberOfClaims: 4352
NumberOfSuppliments: 7047

C:\Users\user\AppData\Local\Temp\ipykernel_7372\1826584962.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df_clean.select_dtypes(include="object").columns:

In [13]:
# Remove leading/trailing spaces from text columns

text_columns = df_clean.select_dtypes(include="object").columns

for col in text_columns:
    df_clean[col] = df_clean[col].str.strip()

C:\Users\user\AppData\Local\Temp\ipykernel_7372\688248711.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df_clean.select_dtypes(include="object").columns

In [14]:
for col in text_columns:
    print("\n" + "=" * 50)
    print(col)
    print(df_clean[col].value_counts(dropna=False).head(20))

==================================================
Month
Month
Jan    1411
May    1367
Mar    1360
Jun    1321
Oct    1305
Dec    1285
Apr    1280
Feb    1266
Jul    1257
Sep    1240
Nov    1201
Aug    1127
Name: count, dtype: int64

==================================================
DayOfWeek
DayOfWeek
Monday       2616
Friday       2445
Tuesday      2300
Thursday     2173
Wednesday    2159
Saturday     1982
Sunday       1745
Name: count, dtype: int64

==================================================
Make
Make
Pontiac      3837
Toyota       3121
Honda        2801
Mazda        2354
Chevrolet    1681
Accura        472
Ford          450
VW            283
Dodge         109
Saab          108
Mercury        83
Saturn         58
Nisson         30
BMW            15
Jaguar          6
Porche          5
Mecedes         4
Ferrari         2
Lexus           1
Name: count, dtype: int64

==================================================
AccidentArea
AccidentArea
Urban    13822
Rural     1598
Name: count, dtype: int64

==================================================
DayOfWeekClaimed
DayOfWeekClaimed
Monday       3757
Tuesday      3375
Wednesday    2951
Thursday     2660
Friday       2497
Saturday      127
Sunday         52
0               1
Name: count, dtype: int64

==================================================
MonthClaimed
MonthClaimed
Jan    1446
May    1411
Mar    1348
Oct    1339
Jun    1293
Feb    1287
Nov    1285
Apr    1271
Sep    1242
Jul    1225
Dec    1146
Aug    1126
0         1
Name: count, dtype: int64

==================================================
Sex
Sex
Male      13000
Female     2420
Name: count, dtype: int64

==================================================
MaritalStatus
MaritalStatus
Married     10625
Single       4684
Divorced       76
Widow          35
Name: count, dtype: int64

==================================================
Fault
Fault
Policy Holder    11230
Third Party       4190
Name: count, dtype: int64

==================================================
PolicyType
PolicyType
Sedan - Collision       5584
Sedan - Liability       4987
Sedan - All Perils      4087
Sport - Collision        348
Utility - All Perils     340
Utility - Collision       30
Sport - All Perils        22
Utility - Liability       21
Sport - Liability          1
Name: count, dtype: int64

==================================================
VehicleCategory
VehicleCategory
Sedan      9671
Sport      5358
Utility     391
Name: count, dtype: int64

==================================================
VehiclePrice
VehiclePrice
20000 to 29000     8079
30000 to 39000     3533
more than 69000    2164
less than 20000    1096
40000 to 59000      461
60000 to 69000       87
Name: count, dtype: int64

==================================================
Days_Policy_Accident
Days_Policy_Accident
more than 30    15247
none               55
8 to 15            55
15 to 30           49
1 to 7             14
Name: count, dtype: int64

==================================================
Days_Policy_Claim
Days_Policy_Claim
more than 30    15342
15 to 30           56
8 to 15            21
none                1
Name: count, dtype: int64

==================================================
PastNumberOfClaims
PastNumberOfClaims
2 to 4         5485
none           4352
1              3573
more than 4    2010
Name: count, dtype: int64

==================================================
AgeOfVehicle
AgeOfVehicle
7 years        5807
more than 7    3981
6 years        3448
5 years        1357
new             373
4 years         229
3 years         152
2 years          73
Name: count, dtype: int64

==================================================
AgeOfPolicyHolder
AgeOfPolicyHolder
31 to 35    5593
36 to 40    4043
41 to 50    2828
51 to 65    1392
26 to 30     613
over 65      508
16 to 17     320
21 to 25     108
18 to 20      15
Name: count, dtype: int64

==================================================
PoliceReportFiled
PoliceReportFiled
No     14992
Yes      428
Name: count, dtype: int64

==================================================
WitnessPresent
WitnessPresent
No     15333
Yes       87
Name: count, dtype: int64

==================================================
AgentType
AgentType
External    15179
Internal      241
Name: count, dtype: int64

==================================================
NumberOfSuppliments
NumberOfSuppliments
none           7047
more than 5    3867
1 to 2         2489
3 to 5         2017
Name: count, dtype: int64

==================================================
AddressChange_Claim
AddressChange_Claim
no change         14324
4 to 8 years        631
2 to 3 years        291
1 year              170
under 6 months        4
Name: count, dtype: int64

==================================================
NumberOfCars
NumberOfCars
1 vehicle      14316
2 vehicles       709
3 to 4           372
5 to 8            21
more than 8        2
Name: count, dtype: int64

==================================================
BasePolicy
BasePolicy
Collision     5962
Liability     5009
All Perils    4449
Name: count, dtype: int64

In [15]:
print(df_clean["FraudFound_P"].value_counts(dropna=False))

FraudFound_P
0    14497
1      923
Name: count, dtype: int64

In [16]:


print("Missing target values:",
      df_clean["FraudFound_P"].isnull().sum())

Missing target values: 0

In [17]:
print("Duplicates:", df_clean.duplicated().sum())

Duplicates: 0

In [18]:
df_clean = df_clean.drop_duplicates().reset_index(drop=True)

In [19]:
print("Duplicates after cleaning:",
      df_clean.duplicated().sum())

Duplicates after cleaning: 0

In [20]:
df_clean.describe()

,WeekOfMonth,WeekOfMonthClaimed,Age,FraudFound_P,PolicyNumber,RepNumber,Deductible,DriverRating,Year
count,15420.000000,15420.000000,15420.000000,15420.000000,15420.000000,15420.000000,15420.000000,15420.000000,15420.000000
mean,2.788586,2.693969,39.855707,0.059857,7710.500000,8.483268,407.704280,2.487808,1994.866472
std,1.287585,1.259115,13.492377,0.237230,4451.514911,4.599948,43.950998,1.119453,0.803313
min,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,300.000000,1.000000,1994.000000
25%,2.000000,2.000000,31.000000,0.000000,3855.750000,5.000000,400.000000,1.000000,1994.000000
50%,3.000000,3.000000,38.000000,0.000000,7710.500000,8.000000,400.000000,2.000000,1995.000000
75%,4.000000,4.000000,48.000000,0.000000,11565.250000,12.000000,400.000000,3.000000,1996.000000
max,5.000000,5.000000,80.000000,1.000000,15420.000000,16.000000,700.000000,4.000000,1996.000000

In [21]:
missing_count = df_clean.isnull().sum()

print(missing_count[missing_count > 0])

Series([], dtype: int64)

In [22]:
for col in df_clean.select_dtypes(include="object").columns:
    values = df_clean[col].astype(str).str.strip().str.lower()

    count = values.isin([
        "unknown",
        "n/a",
        "na",
        "none",
        "?",
        "missing",
        ""
    ]).sum()

    if count > 0:
        print(f"{col}: {count}")

Days_Policy_Accident: 55
Days_Policy_Claim: 1
PastNumberOfClaims: 4352
NumberOfSuppliments: 7047

C:\Users\user\AppData\Local\Temp\ipykernel_7372\2477451355.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df_clean.select_dtypes(include="object").columns:

In [23]:
text_columns = df_clean.select_dtypes(include="object").columns

C:\Users\user\AppData\Local\Temp\ipykernel_7372\2142077968.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df_clean.select_dtypes(include="object").columns

In [24]:
for col in text_columns:
    print("\n" + "=" * 60)
    print("COLUMN:", col)
    print(df_clean[col].value_counts(dropna=False))

============================================================
COLUMN: Month
Month
Jan    1411
May    1367
Mar    1360
Jun    1321
Oct    1305
Dec    1285
Apr    1280
Feb    1266
Jul    1257
Sep    1240
Nov    1201
Aug    1127
Name: count, dtype: int64

============================================================
COLUMN: DayOfWeek
DayOfWeek
Monday       2616
Friday       2445
Tuesday      2300
Thursday     2173
Wednesday    2159
Saturday     1982
Sunday       1745
Name: count, dtype: int64

============================================================
COLUMN: Make
Make
Pontiac      3837
Toyota       3121
Honda        2801
Mazda        2354
Chevrolet    1681
Accura        472
Ford          450
VW            283
Dodge         109
Saab          108
Mercury        83
Saturn         58
Nisson         30
BMW            15
Jaguar          6
Porche          5
Mecedes         4
Ferrari         2
Lexus           1
Name: count, dtype: int64

============================================================
COLUMN: AccidentArea
AccidentArea
Urban    13822
Rural     1598
Name: count, dtype: int64

============================================================
COLUMN: DayOfWeekClaimed
DayOfWeekClaimed
Monday       3757
Tuesday      3375
Wednesday    2951
Thursday     2660
Friday       2497
Saturday      127
Sunday         52
0               1
Name: count, dtype: int64

============================================================
COLUMN: MonthClaimed
MonthClaimed
Jan    1446
May    1411
Mar    1348
Oct    1339
Jun    1293
Feb    1287
Nov    1285
Apr    1271
Sep    1242
Jul    1225
Dec    1146
Aug    1126
0         1
Name: count, dtype: int64

============================================================
COLUMN: Sex
Sex
Male      13000
Female     2420
Name: count, dtype: int64

============================================================
COLUMN: MaritalStatus
MaritalStatus
Married     10625
Single       4684
Divorced       76
Widow          35
Name: count, dtype: int64

============================================================
COLUMN: Fault
Fault
Policy Holder    11230
Third Party       4190
Name: count, dtype: int64

============================================================
COLUMN: PolicyType
PolicyType
Sedan - Collision       5584
Sedan - Liability       4987
Sedan - All Perils      4087
Sport - Collision        348
Utility - All Perils     340
Utility - Collision       30
Sport - All Perils        22
Utility - Liability       21
Sport - Liability          1
Name: count, dtype: int64

============================================================
COLUMN: VehicleCategory
VehicleCategory
Sedan      9671
Sport      5358
Utility     391
Name: count, dtype: int64

============================================================
COLUMN: VehiclePrice
VehiclePrice
20000 to 29000     8079
30000 to 39000     3533
more than 69000    2164
less than 20000    1096
40000 to 59000      461
60000 to 69000       87
Name: count, dtype: int64

============================================================
COLUMN: Days_Policy_Accident
Days_Policy_Accident
more than 30    15247
none               55
8 to 15            55
15 to 30           49
1 to 7             14
Name: count, dtype: int64

============================================================
COLUMN: Days_Policy_Claim
Days_Policy_Claim
more than 30    15342
15 to 30           56
8 to 15            21
none                1
Name: count, dtype: int64

============================================================
COLUMN: PastNumberOfClaims
PastNumberOfClaims
2 to 4         5485
none           4352
1              3573
more than 4    2010
Name: count, dtype: int64

============================================================
COLUMN: AgeOfVehicle
AgeOfVehicle
7 years        5807
more than 7    3981
6 years        3448
5 years        1357
new             373
4 years         229
3 years         152
2 years          73
Name: count, dtype: int64

============================================================
COLUMN: AgeOfPolicyHolder
AgeOfPolicyHolder
31 to 35    5593
36 to 40    4043
41 to 50    2828
51 to 65    1392
26 to 30     613
over 65      508
16 to 17     320
21 to 25     108
18 to 20      15
Name: count, dtype: int64

============================================================
COLUMN: PoliceReportFiled
PoliceReportFiled
No     14992
Yes      428
Name: count, dtype: int64

============================================================
COLUMN: WitnessPresent
WitnessPresent
No     15333
Yes       87
Name: count, dtype: int64

============================================================
COLUMN: AgentType
AgentType
External    15179
Internal      241
Name: count, dtype: int64

============================================================
COLUMN: NumberOfSuppliments
NumberOfSuppliments
none           7047
more than 5    3867
1 to 2         2489
3 to 5         2017
Name: count, dtype: int64

============================================================
COLUMN: AddressChange_Claim
AddressChange_Claim
no change         14324
4 to 8 years        631
2 to 3 years        291
1 year              170
under 6 months        4
Name: count, dtype: int64

============================================================
COLUMN: NumberOfCars
NumberOfCars
1 vehicle      14316
2 vehicles       709
3 to 4           372
5 to 8            21
more than 8        2
Name: count, dtype: int64

============================================================
COLUMN: BasePolicy
BasePolicy
Collision     5962
Liability     5009
All Perils    4449
Name: count, dtype: int64

In [25]:
for col in text_columns:
    print("\n" + "=" * 60)
    print("COLUMN:", col)
    print(df_clean[col].value_counts(dropna=False))

============================================================
COLUMN: Month
Month
Jan    1411
May    1367
Mar    1360
Jun    1321
Oct    1305
Dec    1285
Apr    1280
Feb    1266
Jul    1257
Sep    1240
Nov    1201
Aug    1127
Name: count, dtype: int64

============================================================
COLUMN: DayOfWeek
DayOfWeek
Monday       2616
Friday       2445
Tuesday      2300
Thursday     2173
Wednesday    2159
Saturday     1982
Sunday       1745
Name: count, dtype: int64

============================================================
COLUMN: Make
Make
Pontiac      3837
Toyota       3121
Honda        2801
Mazda        2354
Chevrolet    1681
Accura        472
Ford          450
VW            283
Dodge         109
Saab          108
Mercury        83
Saturn         58
Nisson         30
BMW            15
Jaguar          6
Porche          5
Mecedes         4
Ferrari         2
Lexus           1
Name: count, dtype: int64

============================================================
COLUMN: AccidentArea
AccidentArea
Urban    13822
Rural     1598
Name: count, dtype: int64

============================================================
COLUMN: DayOfWeekClaimed
DayOfWeekClaimed
Monday       3757
Tuesday      3375
Wednesday    2951
Thursday     2660
Friday       2497
Saturday      127
Sunday         52
0               1
Name: count, dtype: int64

============================================================
COLUMN: MonthClaimed
MonthClaimed
Jan    1446
May    1411
Mar    1348
Oct    1339
Jun    1293
Feb    1287
Nov    1285
Apr    1271
Sep    1242
Jul    1225
Dec    1146
Aug    1126
0         1
Name: count, dtype: int64

============================================================
COLUMN: Sex
Sex
Male      13000
Female     2420
Name: count, dtype: int64

============================================================
COLUMN: MaritalStatus
MaritalStatus
Married     10625
Single       4684
Divorced       76
Widow          35
Name: count, dtype: int64

============================================================
COLUMN: Fault
Fault
Policy Holder    11230
Third Party       4190
Name: count, dtype: int64

============================================================
COLUMN: PolicyType
PolicyType
Sedan - Collision       5584
Sedan - Liability       4987
Sedan - All Perils      4087
Sport - Collision        348
Utility - All Perils     340
Utility - Collision       30
Sport - All Perils        22
Utility - Liability       21
Sport - Liability          1
Name: count, dtype: int64

============================================================
COLUMN: VehicleCategory
VehicleCategory
Sedan      9671
Sport      5358
Utility     391
Name: count, dtype: int64

============================================================
COLUMN: VehiclePrice
VehiclePrice
20000 to 29000     8079
30000 to 39000     3533
more than 69000    2164
less than 20000    1096
40000 to 59000      461
60000 to 69000       87
Name: count, dtype: int64

============================================================
COLUMN: Days_Policy_Accident
Days_Policy_Accident
more than 30    15247
none               55
8 to 15            55
15 to 30           49
1 to 7             14
Name: count, dtype: int64

============================================================
COLUMN: Days_Policy_Claim
Days_Policy_Claim
more than 30    15342
15 to 30           56
8 to 15            21
none                1
Name: count, dtype: int64

============================================================
COLUMN: PastNumberOfClaims
PastNumberOfClaims
2 to 4         5485
none           4352
1              3573
more than 4    2010
Name: count, dtype: int64

============================================================
COLUMN: AgeOfVehicle
AgeOfVehicle
7 years        5807
more than 7    3981
6 years        3448
5 years        1357
new             373
4 years         229
3 years         152
2 years          73
Name: count, dtype: int64

============================================================
COLUMN: AgeOfPolicyHolder
AgeOfPolicyHolder
31 to 35    5593
36 to 40    4043
41 to 50    2828
51 to 65    1392
26 to 30     613
over 65      508
16 to 17     320
21 to 25     108
18 to 20      15
Name: count, dtype: int64

============================================================
COLUMN: PoliceReportFiled
PoliceReportFiled
No     14992
Yes      428
Name: count, dtype: int64

============================================================
COLUMN: WitnessPresent
WitnessPresent
No     15333
Yes       87
Name: count, dtype: int64

============================================================
COLUMN: AgentType
AgentType
External    15179
Internal      241
Name: count, dtype: int64

============================================================
COLUMN: NumberOfSuppliments
NumberOfSuppliments
none           7047
more than 5    3867
1 to 2         2489
3 to 5         2017
Name: count, dtype: int64

============================================================
COLUMN: AddressChange_Claim
AddressChange_Claim
no change         14324
4 to 8 years        631
2 to 3 years        291
1 year              170
under 6 months        4
Name: count, dtype: int64

============================================================
COLUMN: NumberOfCars
NumberOfCars
1 vehicle      14316
2 vehicles       709
3 to 4           372
5 to 8            21
more than 8        2
Name: count, dtype: int64

============================================================
COLUMN: BasePolicy
BasePolicy
Collision     5962
Liability     5009
All Perils    4449
Name: count, dtype: int64

In [26]:
text_columns = df_clean.select_dtypes(include="object").columns

C:\Users\user\AppData\Local\Temp\ipykernel_7372\2142077968.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df_clean.select_dtypes(include="object").columns

In [27]:
for col in text_columns:
    df_clean[col] = df_clean[col].str.strip()

print("Whitespace cleaning completed.")

Whitespace cleaning completed.

In [29]:
print("Duplicate rows:", df_clean.duplicated().sum())

Duplicate rows: 0

In [30]:
print(df_clean["FraudFound_P"].value_counts(dropna=False))

FraudFound_P
0    14497
1      923
Name: count, dtype: int64

In [31]:
df_clean.describe().T

,count,mean,std,min,25%,50%,75%,max
WeekOfMonth,15420.0,2.788586,1.287585,1.0,2.00,3.0,4.00,5.0
WeekOfMonthClaimed,15420.0,2.693969,1.259115,1.0,2.00,3.0,4.00,5.0
Age,15420.0,39.855707,13.492377,0.0,31.00,38.0,48.00,80.0
FraudFound_P,15420.0,0.059857,0.237230,0.0,0.00,0.0,0.00,1.0
PolicyNumber,15420.0,7710.500000,4451.514911,1.0,3855.75,7710.5,11565.25,15420.0
RepNumber,15420.0,8.483268,4.599948,1.0,5.00,8.0,12.00,16.0
Deductible,15420.0,407.704280,43.950998,300.0,400.00,400.0,400.00,700.0
DriverRating,15420.0,2.487808,1.119453,1.0,1.00,2.0,3.00,4.0
Year,15420.0,1994.866472,0.803313,1994.0,1994.00,1995.0,1996.00,1996.0

In [32]:
columns_to_check = [
    "AgeOfVehicle",
    "AgeOfPolicyHolder",
    "NumberOfSuppliments",
    "NumberOfCars"
]

for col in columns_to_check:
    print("\n" + "=" * 50)
    print(col)
    print(df_clean[col].value_counts(dropna=False))

==================================================
AgeOfVehicle
AgeOfVehicle
7 years        5807
more than 7    3981
6 years        3448
5 years        1357
new             373
4 years         229
3 years         152
2 years          73
Name: count, dtype: int64

==================================================
AgeOfPolicyHolder
AgeOfPolicyHolder
31 to 35    5593
36 to 40    4043
41 to 50    2828
51 to 65    1392
26 to 30     613
over 65      508
16 to 17     320
21 to 25     108
18 to 20      15
Name: count, dtype: int64

==================================================
NumberOfSuppliments
NumberOfSuppliments
none           7047
more than 5    3867
1 to 2         2489
3 to 5         2017
Name: count, dtype: int64

==================================================
NumberOfCars
NumberOfCars
1 vehicle      14316
2 vehicles       709
3 to 4           372
5 to 8            21
more than 8        2
Name: count, dtype: int64

In [33]:
df_clean["Age"].value_counts(dropna=False).sort_index()

Age
0     320
16      9
17      6
18     48
19     32
     ...
76     42
77     29
78     35
79     20
80     32
Name: count, Length: 66, dtype: int64

In [34]:
df_clean["Age"].describe()

count    15420.000000
mean        39.855707
std         13.492377
min          0.000000
25%         31.000000
50%         38.000000
75%         48.000000
max         80.000000
Name: Age, dtype: float64

In [35]:
df_clean["Year"].value_counts().sort_index()

Year
1994    6142
1995    5195
1996    4083
Name: count, dtype: int64

In [36]:
df_clean["Year"].describe()

count    15420.000000
mean      1994.866472
std          0.803313
min       1994.000000
25%       1994.000000
50%       1995.000000
75%       1996.000000
max       1996.000000
Name: Year, dtype: float64

In [37]:
numeric_columns = df_clean.select_dtypes(include=["int64", "float64"]).columns

print("Numeric columns:")
print(numeric_columns)

Numeric columns:
Index(['WeekOfMonth', 'WeekOfMonthClaimed', 'Age', 'FraudFound_P',
       'PolicyNumber', 'RepNumber', 'Deductible', 'DriverRating', 'Year'],
      dtype='str')

In [38]:
for col in numeric_columns:
    print(
        col,
        "min =", df_clean[col].min(),
        "max =", df_clean[col].max()
    )

WeekOfMonth min = 1 max = 5
WeekOfMonthClaimed min = 1 max = 5
Age min = 0 max = 80
FraudFound_P min = 0 max = 1
PolicyNumber min = 1 max = 15420
RepNumber min = 1 max = 16
Deductible min = 300 max = 700
DriverRating min = 1 max = 4
Year min = 1994 max = 1996

In [39]:
columns_to_check = [
    "AgeOfVehicle",
    "AgeOfPolicyHolder",
    "NumberOfSuppliments",
    "NumberOfCars"
]

for col in columns_to_check:
    print("\n" + "=" * 50)
    print(col)
    print(df_clean[col].value_counts(dropna=False))

==================================================
AgeOfVehicle
AgeOfVehicle
7 years        5807
more than 7    3981
6 years        3448
5 years        1357
new             373
4 years         229
3 years         152
2 years          73
Name: count, dtype: int64

==================================================
AgeOfPolicyHolder
AgeOfPolicyHolder
31 to 35    5593
36 to 40    4043
41 to 50    2828
51 to 65    1392
26 to 30     613
over 65      508
16 to 17     320
21 to 25     108
18 to 20      15
Name: count, dtype: int64

==================================================
NumberOfSuppliments
NumberOfSuppliments
none           7047
more than 5    3867
1 to 2         2489
3 to 5         2017
Name: count, dtype: int64

==================================================
NumberOfCars
NumberOfCars
1 vehicle      14316
2 vehicles       709
3 to 4           372
5 to 8            21
more than 8        2
Name: count, dtype: int64

In [40]:
df_clean[["AgeOfVehicle", "AgeOfVehicle_Clean"]].head(20)

KeyError: "['AgeOfVehicle_Clean'] not in index"

In [41]:
def clean_policy_holder_age(value):
    if pd.isna(value):
        return None

    value = str(value).strip().lower()

    if "over 65" in value:
        return 66

    if "to" in value:
        parts = value.split("to")
        lower = int(parts[0].strip())
        upper = int(parts[1].strip())
        return (lower + upper) / 2

    return None


df_clean["AgeOfPolicyHolder_Clean"] = (
    df_clean["AgeOfPolicyHolder"].apply(clean_policy_holder_age)
)

In [42]:
df_clean[
    ["AgeOfPolicyHolder", "AgeOfPolicyHolder_Clean"]
].drop_duplicates().sort_values("AgeOfPolicyHolder")

    AgeOfPolicyHolder  AgeOfPolicyHolder_Clean
7            16 to 17                     16.5
115          18 to 20                     19.0
5            21 to 25                     23.0
0            26 to 30                     28.0
1            31 to 35                     33.0
6            36 to 40                     38.0
2            41 to 50                     45.5
3            51 to 65                     58.0
10            over 65                     66.0

In [43]:
df_clean["AgeOfPolicyHolder"].value_counts(dropna=False)

AgeOfPolicyHolder
31 to 35    5593
36 to 40    4043
41 to 50    2828
51 to 65    1392
26 to 30     613
over 65      508
16 to 17     320
21 to 25     108
18 to 20      15
Name: count, dtype: int64